title: "W3Craft Blog"
description: Software Development

collections:
  pages:
    output: true
    permalink: ":name"
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
  - scope:
      path: ""
    values:
      layout: "default"
      
baseurl: "" # the subpath of your site, e.g. /w3craft
url: "https://blog.w3craft.ru/" # базовое имя хоста и протокол для вашего сайта, например, http://example.com
copyright: © 2025

plugins:
  - "jekyll-timeago"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jekyll-seo-tag"
